pipeline {
    parameters {
        choice(name: 'PLATFORM_FILTER', choices: ['all', 'linux', 'windows', 'mac'], description: 'Run on specific platform')
    }
    options{
        parallelsAlwaysFailFast()
    }
    agent none
    stages {
        stage('Cross-Browser Selenium tests') {
            matrix {
                agent {
                    label "${PLATFORM}-${BROWSER}"
                }
                when { anyOf {
                        expression { params.PLATFORM_FILTER == 'all' }
                        expression { params.PLATFORM_FILTER == env.PLATFORM }
                } }
                axes {
                    axis {
                        name 'PLATFORM'
                        values 'linux', 'windows', 'mac'
                    }
                    axis {
                        name 'BROWSER'
                        values 'firefox', 'chrome', 'safari', 'edge'
                    }
                }
                excludes {
                    exclude {
                        axis {
                            name 'PLATFORM'
                            values 'linux'
                        }
                        axis {
                            name 'BROWSER'
                            values 'safari'
                        }
                    }
                    exclude {
                        axis {
                            name 'PLATFORM'
                            notValues 'windows'
                        }
                        axis {
                            name 'BROWSER'
                            values 'edge'
                        }
                    }
                }
                stages {
                    stage('Build app for ${PLATFORM} - ${BROWSER}') {
                        steps {
                            echo "Build done for ${PLATFORM} - ${BROWSER}"
                        }
                    }
                    stage('Testing app on ${PLATFORM} - ${BROWSER}') {
                        steps {
                            echo "Tested OK on ${PLATFORM} - ${BROWSER}"
                        }
                    }
                }
            }
        }
    }
}
