pipeline {
  agent {
    label 'docker'
  }
  stages {
    stage("Verify") {
      steps {
        sh '''
          docker version
          docker info
          docker compose version 
        '''
      }
    }
    stage('System prune Docker data') {
      steps {
        sh 'docker system prune -a --volumes -f'
      }
    }
    stage('Docker compose up') {
      steps {
        sh 'docker compose up -d --no-color --wait -f examples/02-docker/07-docker-compose/docker-compose.yaml'
        sh 'docker compose ps'
      }
    }
    stage('Test the container app') {
      steps {
          script{
            docker.image('brainupgrade/tshoot').inside {
                          sh 'curl http://echo-server:8080'

            }
        }
      }
    }
  }
  post {
    always {
      sh 'docker compose down --remove-orphans -v'
      sh 'docker compose ps'
    }
  }
}