pipeline {
  agent {
  docker {
    image 'node:20-alpine3.17'
    label 'docker'
    reuseNode true
  }
}

  stages {
    stage('Verify') {
      steps {
        sh 'node --version'
      }
    }
  }
}