@Library('my-pipeline-lib') _ // Load the shared library

pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    // Load the shared library from its repository
                    library identifier: 'my-pipeline-lib@main', retriever: modernSCM(
                        [$class: 'GitSCMSource',
                         remote: 'https://github.com/brainupgrade-in/jenkins-shared-libs.git',
                         credentialsId: 'bu-github-credentials'])
                      
                    // Use the shared library function to build the Java app
                    myPipelineLib.buildJavaApp()
                }
            }
        }
    }
}
