podTemplate(inheritFrom: 'docker', containers: [containerTemplate(image: 'brainupgrade/tshoot', name: 'test', command: 'cat', ttyEnabled: true)]) {
    podTemplate(containers: [containerTemplate(image: 'maven', name: 'maven', command: 'cat', ttyEnabled: true)]) {
      node(POD_LABEL) { // gets a pod with both docker and maven

        container('docker'){
          sh 'sleep 30'
          sh 'docker info'
        }
        container('maven'){
          sh 'mvn --version'
          sh 'echo hello $POD_CONTAINER_NAME'
        }
      }
    }
}