pipeline {
  // agent { dockerfile true }
  agent {
    dockerfile {
      dir 'examples/02-docker/06-dockerfile'
      filename 'Dockerfile'
      label 'docker'
    }
  }

  stages {
    stage('Test') {
      steps {
        sh '''
          node --version
          git --version
          curl --version
        '''
      }
    }
  }
}