podTemplate(containers: [
    containerTemplate(name: 'maven', image: 'adoptopenjdk/maven-openjdk11', command: 'sleep', args: '99d'),
    containerTemplate(name: 'golang', image: 'golang:1.21.1', command: 'sleep', args: '99d')
  ]) {

    node(POD_LABEL) {
        stage('Maven project') {
            git url: 'https://github.com/brainupgrade-in/request-logger', branch: 'main'
            container('maven') {
                stage('Build Request Logger') {
                    sh 'mvn -B -ntp clean install'
                }
            }
        }

        stage('Golang project') {
            container('golang') {
                stage('Build Terraform') {
                    sh '''
                    git clone https://github.com/hashicorp/terraform.git
                    cd terraform && make
                    '''
                }
            }
        }

    }
}