pipeline {
  agent {
    kubernetes {
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: dind
    image: brainupgrade/docker:20-dind
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ''
    securityContext:
      privileged: true
  - name: docker
    env:
    - name: DOCKER_HOST
      value: 127.0.0.1
    image: docker
    command:
    - cat
    tty: true
"""
    }
  }
  stages {
    stage('Build') {
      steps {
        git url: 'https://github.com/brainupgrade-in/gitops-apps-hello', branch: 'main'
        container('dind'){
            sh "/bin/bash -c echo -n 'Waiting for port 2375 to open...' && until nc -z 0.0.0.0 2375; do sleep 1 && echo -n .; done && echo 'Port 2375 is now open!'"
        }
        container('docker') {
          withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
            sh "docker login -u ${USERNAME} -p ${PASSWORD}"
            sh "docker build --build-arg='BUILD_ID=${env.BUILD_ID}' --build-arg='GIT_COMMIT_ID=${env.GIT_COMMIT}' -t brainupgrade/hello:${env.GIT_COMMIT} ."
          }
        }
      }
    }
  }
}
