pipeline {
    agent {
      label 'docker'
    }
    stages {
        stage('Build & Deliver') {
            steps {
              script{
                    withDockerContainer(args: '-p 3306:3306', image: 'mysql:8-oracle') {
                        /* do things */
                        sh 'echo hello'
                        sh 'ps aux'
                    }
              }
            }
        }
    }
}
