pipeline {
    agent {
      label 'docker'
    }
    stages {
        stage('Build & Deliver') {
            steps {
              script{
                    docker.image('mysql:8-oracle').withRun('-p 3306:3306') {
                        /* do things */
                        sh 'echo hello'
                        sh 'ps aux'
                    }
              }
            }
        }
    }
}
