pipeline {
    agent {
      label 'docker'
    }
    stages {
        stage('Testing Database') {
            steps {
              script{
                    withDockerContainer(args: '-p 3306:3306', image: 'mysql:8-oracle') {
                        sh 'mysql -V'
                    }
              }
            }
        }
        stage('Network tests') {
            steps {
              script{
                    withDockerContainer(image: 'brainupgrade/tshoot') {
                        sh 'nc -vz google.com:80'
                    }
              }
            }
        }
    }
}
