pipeline{
    agent {
    kubernetes {
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jmeter
    image: egaillardon/jmeter
    command:
    - cat
    tty: true
"""
    }
  }
    
    stages{
        stage('test'){
            steps{
                // git branch: 'main', url: 'https://github.com/brainupgrade-in/spring-framework-petclinic'
                git branch: 'main', url: 'https://github.com/brainupgrade-in/jenkins'
                script{
                    container('jmeter'){
                        // sh "rm -rf result && rm -rf result.jtl && jmeter -n -t ${env.WORKSPACE}/src/test/jmeter/petclinic_test_plan.jmx -l result.jtl -e -o result"
                        sh "rm -rf result && rm -rf result.jtl && jmeter -n -t ${env.WORKSPACE}/src/test/resources/jmeter-e2e.jmx -l result.jtl -e -o result"
                        perfReport filterRegex: '', sourceDataFiles: '**/*.jtl'
                    }
                }
            }
        }
        
        stage('report'){
            steps{
                script{
                    container('jmeter'){
                        publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: 'result', reportFiles: 'index.html', reportName: 'JMeter-Report', reportTitles: ''])
                    }
                }
            }
        }
    }
}