pipeline {
    agent {
      label 'docker'
    }
    stages {
        stage('NPM Build') {
      steps {
        git branch: 'master', url: 'https://github.com/brainupgrade-in/nodejsappdocker'
        script {
          docker.image('node:20-alpine3.17').inside {
            sh 'npm install'
          }
        }
      }
        }
        stage('NPM Test') {
          parallel {
            stage('Run app for testing') {
            steps {
              script {
              withDockerContainer(args: '--name test -p 8000:8000', image: 'node:20-alpine3.17') {
                sh 'npm start &'
              }
              }
            }
            }
            stage('Test app while it is running') {
            steps {
              retry(5) {
                timeout(time: 1, unit: 'MINUTES') {
                    script {
                    withDockerContainer(args: '--link test:test', image: 'brainupgrade/tshoot') {
                      sh 'nc -vz test:8000'
                    }
                    }
              }
              }
            }
            post {
              always {
                  sh 'docker stop test && docker rm test'
              }
            }
            }
          }
        }
    }
}
