pipeline {
    agent {
      label 'docker'
    }
    stages {
        stage('Build & Unit Test') {
            steps {
              script{
                    withDockerContainer(image: 'maven:3.3.3-jdk-8') {  
                      git branch: 'master', url: 'https://github.com/jglick/simple-maven-project-with-tests'
                      sh 'mvn -Dmaven.test.failure.ignore install'
                      junit '**/target/surefire-reports/TEST-*.xml'
                    }
              }
            }
        }
    }
}