podTemplate(yaml: '''
              apiVersion: v1
              kind: Pod
              metadata:
                labels:
                  some-label: some-label-value
              spec:
                containers:
                - name: test
                  image: brainupgrade/tshoot
                  command:
                  - sleep
                  args:
                  - 99d
                  tty: true
                - name: mongo
                  image: mongo
''') {
  node(POD_LABEL) {
    stage('Integration Test') {
      try {
        container('test') {
          sh 'nc -vz -w 60 localhost:27017 '
          def mongoLog = containerLog(name: 'mongo', returnLog: true, tailingLines: 5, sinceSeconds: 20, limitBytes: 50000)
          // assert mongoLog.contains('Waiting for connections')
          sh 'echo performed real integration tests'
        }
      } catch (Exception e) {
        containerLog 'mongo'
        // throw e
      }
    }
  }
}